[package]
edition = "2021"
name    = "l1"
version = "0.1.0"

[dependencies]
bit-set           = "0.8.0"
crossbeam-channel = "0.5.13"
expect-test       = "1.5.0"
num-bigint        = "0.4.6"
tokio             = { version = "1.40.0", features = ["full"] }
tokio-util        = "0.7.12"
